@startuml Histoire de nos villes
left to right direction
actor Utilisateur as u
actor Support as s
actor Client as c

rectangle "Histoire de nos villes" {
  (UC1).>(Etre notifié des points d'interets)
  usecase "Découvrir une ville" as UC1
  (UC1).>(Etre geolocalisé)
  usecase "Remplir les informations historiques" as UC4
  usecase "Acheter la solution" as UC5
  (UC5).>(Donner les informations des points d'interets)
}

u --> UC1
s --> UC4
c --> UC5

@enduml
